from prj_gen.generator import Gen
from .external import get_license, run_cmd

class MyGen(Gen):
    @classmethod
    def pre_process(cls, ctx, params):
        run_cmd("poetry", params["path"])
        run_cmd("git", params["path"])
        if ctx['licfile']:
            get_license(params["path"])
        ctx["pre_injected"] = "generated by gitize project generator"

    @classmethod
    def post_process(cls, ctx, params):
        ctx["post_injected"] = "post_injected_value"
