from prj_gen.generator import Gen, PARAM_TARGET
from .external import write_license, run_cmd

class MyGen(Gen):
    @classmethod
    def pre_process(cls, ctx, params):
        run_cmd("poetry", params[PARAM_TARGET])
        run_cmd("git", params[PARAM_TARGET])
        if ctx['licfile']:
            write_license(params[PARAM_TARGET])
        ctx["pre_injected"] = "generated by gitize project generator"

    @classmethod
    def post_process(cls, ctx, params):
        ctx["post_injected"] = "post_injected_value"
